(() => {
  const KEY = "katris-travel:feature-state-v2";
  const ROUTES = [
    {id:"fjord",type:"nature",kicker:"Norway / 7 nights",title:"Bergen to Flam by rail and ferry",summary:"Scenic rail, ferry movement and one flexible weather day.",to:"Bergen",length:"7 nights",budget:"1800 EUR",stay:"Quiet waterfront or station stay",move:"Rail + ferry",pillars:["Scenery","Quiet stays","Rail or ferry"],note:"Bergen arrival. Flam Railway and Aurlandsfjord ferry. Keep one flexible weather day and avoid tight same-day transfers.",ask:"Build a 7-night Bergen to Flam trip using scenic rail and ferry, quiet stays and one flexible weather day.",fallback:"Confirm rail and ferry schedules with the operating supplier."},
    {id:"stockholm",type:"city",kicker:"Sweden / 5 nights",title:"Stockholm design and archipelago break",summary:"Museums, walkable neighborhoods, one island day and open evenings.",to:"Stockholm",length:"5 nights",budget:"1500 EUR",stay:"Sodermalm or central transit stay",move:"Metro + local ferry",pillars:["Local culture","Quiet stays","Rail or ferry"],note:"Base in Stockholm. Add one museum block, one archipelago day and one unscheduled evening. Favor easy transit over nightlife zones.",ask:"Create a 5-night Stockholm design and archipelago itinerary with museums, local ferry travel and quiet evenings.",fallback:"Archipelago departures are seasonal and require date-specific confirmation."},
    {id:"copenhagen",type:"city",kicker:"Denmark / 5 nights",title:"Copenhagen coast, cycling and galleries",summary:"Cycling, Louisiana Museum, coastal trains and unhurried meals.",to:"Copenhagen",length:"5 nights",budget:"1400 EUR",stay:"Central or Norrebro stay near metro",move:"Bike + regional rail",pillars:["Local culture","Scenery"],note:"Copenhagen base. Include Louisiana Museum by regional rail, one coastal cycling block and a weather-proof indoor alternative.",ask:"Plan a 5-night Copenhagen trip with cycling, Louisiana Museum, coastal rail and a weather-proof backup.",fallback:"Confirm bike access and museum opening hours for the selected date."},
    {id:"lapland",type:"winter",kicker:"Finland / 7 nights",title:"Lapland cabin and aurora rhythm",summary:"Sauna, short outdoor blocks, recovery time and flexible aurora evenings.",to:"Helsinki",length:"7 nights",budget:"2400 EUR",stay:"Cabin with local transfer support",move:"Flight + local shuttle",pillars:["Scenery","Quiet stays","Wellness"],note:"Use Helsinki as the gateway, then continue to Lapland. Keep outdoor blocks short and treat aurora viewing as weather-dependent.",ask:"Build a 7-night Finland and Lapland cabin trip with sauna, short winter activities and flexible aurora evenings.",fallback:"Aurora visibility is not guaranteed; confirm transfers and pickup points."},
    {id:"reykjavik",type:"nature",kicker:"Iceland / 7 nights",title:"Reykjavik base with two slow landscape days",summary:"A base-first route that limits hotel changes and weather risk.",to:"Reykjavik",length:"7 nights",budget:"2200 EUR",stay:"Central Reykjavik with breakfast",move:"Guided day trip or rental car",pillars:["Scenery","Quiet stays"],note:"Stay mainly in Reykjavik. Add two landscape days with weather alternatives and one geothermal recovery block.",ask:"Create a 7-night Reykjavik-based trip with two landscape days, weather alternatives and geothermal recovery.",fallback:"Check road conditions and excursion operation close to departure."},
    {id:"helsinki",type:"city",kicker:"Finland + Estonia / 5 nights",title:"Helsinki and Tallinn by ferry",summary:"One clear crossing, compact old-town walking and a light ferry day.",to:"Helsinki",length:"5 nights",budget:"1200 EUR",stay:"Helsinki center + Tallinn old-town edge",move:"Ferry + tram",pillars:["Local culture","Rail or ferry"],note:"Split the route between Helsinki and Tallinn. Keep the ferry day light and avoid fixed bookings immediately after arrival.",ask:"Plan a 5-night Helsinki and Tallinn trip with a relaxed ferry day, local culture and transit-based stays.",fallback:"Confirm ferry schedules and terminal details for the chosen date."}
  ];
  const GUIDES = [
    {id:"pace",title:"Set the pace before choosing attractions",tip:"Use relaxed pacing. Protect arrival and transfer days and leave one flexible weather or fatigue block."},
    {id:"stay",title:"Rank stays by transit, quiet and total friction",tip:"Rank stays by transit ease, quiet, late-arrival practicality and total transfer friction. Treat unverified prices as provisional."},
    {id:"provider",title:"Separate inspiration from supplier confirmation",tip:"Keep a supplier confirmation step for final price, inventory, cancellation terms and operating status."}
  ];
  const SEEDS = [
    {id:"s1",name:"Mara",route:"Bergen → Flam",note:"Moving the ferry day away from arrival made the route much calmer.",routeId:"fjord",helpful:12},
    {id:"s2",name:"Jon",route:"Stockholm",note:"One archipelago day was enough; the open final evening mattered.",routeId:"stockholm",helpful:8},
    {id:"s3",name:"Anika",route:"Helsinki → Lapland",note:"Aurora plans worked best as optional evening blocks, not promises.",routeId:"lapland",helpful:15}
  ];
  const fresh = () => ({saved:[],posts:[],helpful:{},board:{destination:"Not selected",stay:"Not selected",transport:"Not selected",priority:"Not selected",provider:"Waiting for planner analysis",fallback:"No fallback note yet",export:"Not copied",source:"Planner inputs"}});
  let state = (() => { try { return {...fresh(),...JSON.parse(localStorage.getItem(KEY)||"{}")}; } catch { return fresh(); } })();
  state.board = {...fresh().board,...(state.board||{})}; state.saved ||= []; state.posts ||= []; state.helpful ||= {};
  const save = () => localStorage.setItem(KEY, JSON.stringify(state));
  const esc = (v) => String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const byId = (id) => ROUTES.find(r=>r.id===id);
  const scroll = (id) => document.querySelector(id)?.scrollIntoView({behavior:"smooth",block:"start"});
  const setField = (id,value) => { const e=document.querySelector(id); if(!e)return; e.value=value; e.dispatchEvent(new Event("input",{bubbles:true})); e.dispatchEvent(new Event("change",{bubbles:true})); };
  function install(){
    if(document.querySelector("#discover")) return;
    const inspiration=document.querySelector(".inspiration-strip"), destinations=document.querySelector("#destinations"), planner=document.querySelector("#planner");
    if(!inspiration||!destinations||!planner)return;
    inspiration.insertAdjacentHTML("afterend",`<section class="feature-section" id="discover"><div class="feature-heading"><div><p class="eyebrow">Finite discovery stream</p><h2>Choose a useful route idea, not an endless feed.</h2></div><p>Six practical directions. Save one, send it to the planner, or turn it into an assistant prompt.</p></div><div class="feature-filters"><button class="is-active" data-filter="all">All routes</button><button data-filter="nature">Nature</button><button data-filter="city">City</button><button data-filter="winter">Winter</button><span id="discovery-count"></span></div><div class="discovery-grid" id="discovery-grid"></div></section>`);
    destinations.insertAdjacentHTML("afterend",`<section class="feature-section" id="guides"><div class="feature-heading"><div><p class="eyebrow">Short guidance surface</p><h2>One planning decision at a time.</h2></div><p>Finite motion guides with transcripts, not fake live destination footage.</p></div><div class="guidance-grid" id="guidance-grid"></div></section><section class="feature-section" id="community"><div class="feature-heading"><div><p class="eyebrow">Lightweight community preview</p><h2>Use traveler notes as planning evidence.</h2></div><p>Examples and browser-only notes are labeled separately.</p></div><div class="community-layout"><div id="community-list"></div><form id="community-form" class="community-form"><p class="eyebrow">Add a local note</p><h3>Record what another traveler should know.</h3><label><span>Name</span><input name="name" maxlength="30" required></label><label><span>Route</span><select name="route">${ROUTES.map(r=>`<option value="${r.id}">${esc(r.title)}</option>`).join("")}</select></label><label><span>Note</span><textarea name="note" maxlength="220" rows="4" required></textarea></label><button class="secondary-button" type="submit">Save local note</button><p id="community-status" aria-live="polite"></p></form></div></section>`);
    planner.insertAdjacentHTML("beforebegin",`<section class="feature-section" id="route-board"><div class="feature-heading"><div><p class="eyebrow">Route board</p><h2>Keep the current travel decision visible.</h2></div><p>Planner inputs, saved route context, provider status, fallback and export state.</p></div><div class="route-board-grid" id="route-board-grid"></div><div class="feature-actions"><button class="secondary-button" data-open-planner>Open planner</button><button class="ghost-button" data-copy-board>Copy route board</button><button class="ghost-button" data-clear-board>Clear route board</button></div><p id="route-board-status" aria-live="polite"></p></section>`);
    const nav=document.querySelector(".site-nav"); [["Discover","#discover"],["Guides","#guides"],["Community","#community"],["Route board","#route-board"]].forEach(([t,h])=>{if(nav&&!nav.querySelector(`[href="${h}"]`)){const a=document.createElement("a");a.href=h;a.textContent=t;nav.append(a);}});
  }
  function renderRoutes(filter="all"){
    const list=filter==="all"?ROUTES:ROUTES.filter(r=>r.type===filter), grid=document.querySelector("#discovery-grid"); if(!grid)return;
    document.querySelector("#discovery-count").textContent=`${list.length} of ${ROUTES.length} routes`;
    grid.innerHTML=list.map(r=>`<article class="discovery-card"><div class="card-head"><p class="eyebrow">${esc(r.kicker)}</p><button data-save="${r.id}" aria-pressed="${state.saved.includes(r.id)}">${state.saved.includes(r.id)?"Saved":"Save"}</button></div><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p><dl><div><dt>Stay</dt><dd>${esc(r.stay)}</dd></div><div><dt>Move</dt><dd>${esc(r.move)}</dd></div></dl><div class="feature-actions"><button class="primary-button" data-use="${r.id}">Use in planner</button><button class="ghost-button" data-ask="${r.id}">Ask assistant</button></div></article>`).join("");
  }
  function renderGuides(){ const g=document.querySelector("#guidance-grid"); if(g)g.innerHTML=GUIDES.map((x,i)=>`<article class="guidance-card" data-guide-card="${x.id}"><div class="guide-stage"><strong>0${i+1}</strong><span></span></div><p class="eyebrow">20-second motion guide</p><h3>${esc(x.title)}</h3><p>${esc(x.tip)}</p><div class="guide-progress"><span></span></div><div class="feature-actions"><button class="secondary-button" data-play="${x.id}">Play guide</button><button class="ghost-button" data-tip="${x.id}">Use tip in planner</button></div></article>`).join(""); }
  function renderCommunity(){ const el=document.querySelector("#community-list"); if(!el)return; el.innerHTML=[...SEEDS,...state.posts].map(p=>`<article class="community-card"><p class="eyebrow">${p.local?"Saved in this browser":"Example traveler note"}</p><div class="card-head"><h3>${esc(p.route)}</h3><span>${esc(p.name)}</span></div><blockquote>${esc(p.note)}</blockquote><div class="feature-actions"><button class="ghost-button" data-helpful="${p.id}">Helpful ${(p.helpful||0)+(state.helpful[p.id]||0)}</button><button class="secondary-button" data-use="${p.routeId}">Use this route</button></div></article>`).join(""); }
  function renderBoard(){ const b=state.board, el=document.querySelector("#route-board-grid"); if(!el)return; el.innerHTML=[["Destination",b.destination],["Saved stay",b.stay],["Transport",b.transport],["Priority",b.priority],["Provider status",b.provider],["Fallback note",b.fallback],["Export state",b.export],["Source",b.source]].map(([k,v])=>`<article><p class="eyebrow">${k}</p><strong>${esc(v)}</strong></article>`).join(""); }
  function useRoute(r,source="Discovery route"){
    setField("#to",r.to); setField("#tripLength",r.length); setField("#budget",r.budget);
    const notes=document.querySelector("#notes"); if(notes){notes.value=[notes.value.trim(),r.note].filter(Boolean).join("\n"); notes.dispatchEvent(new Event("input",{bubbles:true}));}
    document.querySelectorAll('input[name="pillars"]').forEach(e=>{if(r.pillars.includes(e.value))e.checked=true;});
    state.board={...state.board,destination:r.to,stay:r.stay,transport:r.move,priority:r.pillars.join(", "),fallback:r.fallback,export:"Not copied",source}; save(); renderBoard(); scroll("#planner");
  }
  function syncBoard(){ const to=document.querySelector("#to")?.value.trim(), priorities=[...document.querySelectorAll('input[name="pillars"]:checked')].map(x=>x.value); if(to)state.board.destination=to; if(priorities.length)state.board.priority=priorities.join(", "); save(); renderBoard(); }
  function bind(){
    document.addEventListener("click",async e=>{
      const f=e.target.closest("[data-filter]"); if(f){document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("is-active",x===f));renderRoutes(f.dataset.filter);return;}
      const s=e.target.closest("[data-save]"); if(s){state.saved=state.saved.includes(s.dataset.save)?state.saved.filter(x=>x!==s.dataset.save):[...state.saved,s.dataset.save];save();renderRoutes(document.querySelector("[data-filter].is-active")?.dataset.filter||"all");return;}
      const u=e.target.closest("[data-use]"); if(u){const r=byId(u.dataset.use);if(r)useRoute(r,u.closest(".community-card")?"Community note":"Discovery route");return;}
      const a=e.target.closest("[data-ask]"); if(a){const r=byId(a.dataset.ask),input=document.querySelector("#assistant-input");if(r&&input){input.value=r.ask;scroll("#assistant");input.focus({preventScroll:true});}return;}
      const p=e.target.closest("[data-play]"); if(p){const card=p.closest(".guidance-card"),bar=card.querySelector(".guide-progress span");card.classList.toggle("is-playing");bar.style.animation="none";requestAnimationFrame(()=>bar.style.animation=card.classList.contains("is-playing")?"guideProgress 20s linear forwards":"none");p.textContent=card.classList.contains("is-playing")?"Pause guide":"Play guide";return;}
      const t=e.target.closest("[data-tip]"); if(t){const guide=GUIDES.find(x=>x.id===t.dataset.tip),n=document.querySelector("#notes");if(guide&&n){n.value=[n.value.trim(),guide.tip].filter(Boolean).join("\n");syncBoard();scroll("#planner");}return;}
      const h=e.target.closest("[data-helpful]"); if(h){state.helpful[h.dataset.helpful]=(state.helpful[h.dataset.helpful]||0)+1;save();renderCommunity();return;}
      if(e.target.closest("[data-open-planner]")){scroll("#planner");return;}
      if(e.target.closest("[data-clear-board]")){state.board=fresh().board;save();renderBoard();document.querySelector("#route-board-status").textContent="Route board cleared; planner fields were not changed.";return;}
      if(e.target.closest("[data-copy-board]")){syncBoard();const b=state.board,text=`Katris route board\nDestination: ${b.destination}\nStay: ${b.stay}\nTransport: ${b.transport}\nPriority: ${b.priority}\nProvider: ${b.provider}\nFallback: ${b.fallback}`;try{await navigator.clipboard.writeText(text);b.export="Copied to clipboard";document.querySelector("#route-board-status").textContent="Route board copied.";}catch{b.export="Copy blocked by browser";document.querySelector("#route-board-status").textContent="Clipboard access was blocked.";}save();renderBoard();}
    });
    document.querySelector("#community-form")?.addEventListener("submit",e=>{e.preventDefault();const d=new FormData(e.currentTarget),r=byId(String(d.get("route")));if(!r)return;state.posts.push({id:`local-${Date.now()}`,name:String(d.get("name")).trim(),route:r.title,note:String(d.get("note")).trim(),routeId:r.id,helpful:0,local:true});state.posts=state.posts.slice(-8);save();renderCommunity();e.currentTarget.reset();document.querySelector("#community-status").textContent="Saved in this browser. It was not published online.";});
    document.querySelector("#planner-form")?.addEventListener("input",syncBoard);
    const ops=document.querySelector("#ops-monitor"); if(ops)new MutationObserver(()=>{state.board.provider=[ops.querySelector("h3")?.textContent,ops.querySelector("p:last-child")?.textContent].filter(Boolean).join(" — ");save();renderBoard();}).observe(ops,{childList:true,subtree:true,characterData:true});
  }
  function init(){install();renderRoutes();renderGuides();renderCommunity();syncBoard();bind();}
  document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init,{once:true}):init();
})();